config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "users#index"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    validates :username , presence: true
    
    validates :email , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index 
        @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
   def new 

    @user = User.new

   end
   def edit 
    @user = User.find(params[:id])
   end
   def update 
 
    @user = User.new(users_params)
        
    if @user.save
      redirect_to new_user_path
    else
      render :new, status: :unprocessable_entity
    end

   end
    def create
      #@user = User.new(username: params[:username], email: params[:email], password: params[:password])
        @user = User.new(users_params)
        
      if @user.save
        redirect_to new_user_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    private 
    def users_params

        params.require(:user).permit(:username, :email,:password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReFormer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<h1>Create Your Profile<h1>
<%=form_with model: @user do|form|%>
<div>
<%=form.label :username%><br>
<%= form.text_field :username ,placeholder: "User Name"%>
</div>



<div>
<%=form.label :email%><br>
<%= form.text_field :email, placeholder: "Email"%>
</div>



<div>
<%=form.label :password%><br>
<%= form.password_field :email, placeholder: "Password"%>

</div>

<%=form.submit%>
<%end%>
<%=link_to "All Users" ,users_path%>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>
<%= render partial: "shared/form",user: @user%>

app/views/users/index.html.erb
<h1>all Useres</h1>
<%@users.each do |user|%><b>
 <%= link_to user.username ,user%></b><br>
<%end%>

<div class = "mb-3" >
<%= link_to "Create Profile",new_user_path%>
</div>

app/views/users/new.html.erb
<%=render partial: "shared/form",user: @user%>

app/views/users/show.html.erb
<h1>All Users</h1>
<%=@user.username%>
<br>
<%=@user.email%>
<%=link_to "Edit your Profile",edit_user_path(@user)%>